/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mao_archive_libzip_ZipFile */

#ifndef _Included_mao_archive_libzip_ZipFile
#define _Included_mao_archive_libzip_ZipFile
#ifdef __cplusplus
extern "C" {
#endif
#undef mao_archive_libzip_ZipFile_ZIP_CREATE
#define mao_archive_libzip_ZipFile_ZIP_CREATE 1L
#undef mao_archive_libzip_ZipFile_ZIP_EXCL
#define mao_archive_libzip_ZipFile_ZIP_EXCL 2L
#undef mao_archive_libzip_ZipFile_ZIP_CHECKCONS
#define mao_archive_libzip_ZipFile_ZIP_CHECKCONS 4L
#undef mao_archive_libzip_ZipFile_ZIP_TRUNCATE
#define mao_archive_libzip_ZipFile_ZIP_TRUNCATE 8L
#undef mao_archive_libzip_ZipFile_ZIP_RDONLY
#define mao_archive_libzip_ZipFile_ZIP_RDONLY 16L
/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mao_archive_libzip_ZipFile_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    open
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntriesCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_getEntriesCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    removeEntry
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_mao_archive_libzip_ZipFile_removeEntry
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    renameEntry
 * Signature: (JJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_mao_archive_libzip_ZipFile_renameEntry
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    addFileEntry
 * Signature: (J[BLjava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_addFileEntry
  (JNIEnv *, jclass, jlong, jbyteArray, jstring, jlong, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    addBufferEntry
 * Signature: (J[B[B)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_addBufferEntry
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    addDirectoryEntry
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_addDirectoryEntry
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    nameLocate
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_nameLocate
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    openEntryStat
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_openEntryStat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryName
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mao_archive_libzip_ZipFile_getEntryName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntrySize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_getEntrySize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryCSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_getEntryCSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryMTime
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_getEntryMTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryCrc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_getEntryCrc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mao_archive_libzip_ZipFile_getEntryMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryEncryptionMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mao_archive_libzip_ZipFile_getEntryEncryptionMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_mao_archive_libzip_ZipFile_getEntryFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    freeEntryStat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mao_archive_libzip_ZipFile_freeEntryStat
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getEntryComment
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mao_archive_libzip_ZipFile_getEntryComment
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    setEntryMTime
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_mao_archive_libzip_ZipFile_setEntryMTime
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    setEntryEncryptionMethod
 * Signature: (JJILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_mao_archive_libzip_ZipFile_setEntryEncryptionMethod
  (JNIEnv *, jclass, jlong, jlong, jint, jstring);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    setEntryMethod
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_mao_archive_libzip_ZipFile_setEntryMethod
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    setEntryComment
 * Signature: (JJ[B)Z
 */
JNIEXPORT jboolean JNICALL Java_mao_archive_libzip_ZipFile_setEntryComment
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    getComment
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mao_archive_libzip_ZipFile_getComment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    setComment
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_mao_archive_libzip_ZipFile_setComment
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    openEntry
 * Signature: (JJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_openEntry
  (JNIEnv *, jclass, jlong, jlong, jstring);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    readEntryBytes
 * Signature: (J[BII)J
 */
JNIEXPORT jlong JNICALL Java_mao_archive_libzip_ZipFile_readEntryBytes
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    closeEntry
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mao_archive_libzip_ZipFile_closeEntry
  (JNIEnv *, jclass, jlong);

/*
 * Class:     mao_archive_libzip_ZipFile
 * Method:    close
 * Signature: (JLmao/archive/libzip/ProgressListener;)V
 */
JNIEXPORT void JNICALL Java_mao_archive_libzip_ZipFile_close
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
